CREATE EXTENSION ltree;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS 'uuid-ossp';

CREATE TABLE IF NOT EXISTS users (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS data.sessions(
    id SERIAL PRIMARY KEY,
    guid_id uuid NOT NULL DEFAULT public.uuid_generate_v4(),
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    session_data JSONB NOT NULL,
    data_created TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    data_expired TIMESTAMP WITHOUT TIME ZONE,
)

GRANT USAGE ON SCHEMA data TO datanator;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA data TO datanator;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA data TO GROUP datanator;